# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server Node.js CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/server-node.js.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "server/"
        TARGET: ${{ secrets.REMOTE_TARGET_SERVER }}
        EXCLUDE: '/node_modules/*,/.git/*,/.github/*,/tests/*,/*.md'
  
  serve:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies and Restart Server
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        script: |
          cd ${{ secrets.REMOTE_TARGET_SERVER }}
          npm install --production
          pm2 restart unbox-server
